### ISSUE TITLE
Type error: Cannot Read Properties....

### ISSUE THREAD

**Issue by ams-ryanolson** [vinayakkulkarni/v-clappr#912]
Error:
`Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'configure')
    at Proxy.configure (clappr-core.esm.js:7738:17)
    at VClappr.vue:167:28`

I am using either example you have on your GH page. This seems to only occur when using V3 version.

**Comment by vinayakkulkarni** [comment]
Fixed in `v3.1.x`

**Comment by ams-ryanolson** [comment]
Unfortunately it is not resolved. I am receiving the same error using Example 2 on a Vue 3 project

**Comment by vinayakkulkarni** [comment]
> Unfortunately it is not resolved. I am receiving the same error using Example 2 on a Vue 3 project

try `rm -rf node_modules package-lock.json yarn.lock && npm i` ?

**Comment by vinayakkulkarni** [comment]
Can you do a stackblitz or codesandbox repro?
